arm_dynamic_controller:
  type: "effort_controllers/DirectDynamicController"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    #- arm_5_joint
    #- arm_6_joint
    #- arm_7_joint

  Kp: 100.0 #10000
  Kv: 20.0  #1000
  controller_type: "PD+"
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    arm_left_1_joint:
      goal: 0.02
    arm_left_2_joint:
      goal: 0.02
    arm_left_3_joint:
      goal: 0.02
    arm_left_4_joint:
      goal: 0.02
